

name: Show file content of checkout action

on:
    workflow_dispatch:

jobs:
    display:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: list files
              run: ls -lrth

            - name: create a file
              run: echo "Hi Hello" > sample.txt

            - name: display file content
              run: cat sample.txt

