

name: Multi-line command

on: workflow_dispatch

jobs:
    display:
        runs-on: ubuntu-latest
        steps:
            - name: Multiple commands in one step
              run: |
                echo "This is line-1"
                echo "This is line-2"
                ls -lrt
                date

                