

name: Parallel jobs execution 

on: workflow_dispatch

jobs:
    job1: 
        runs-on: ubuntu-latest
        steps:
            - name: job1 step
              run: echo "This is job1 execution"

    job2:
        runs-on: ubuntu-latest
        steps:
            - name: job2 step
              run: echo "This is job2 execution"